"""Added game player participant tables

Revision ID: 879e3970c027
Revises: 
Create Date: 2022-11-12 20:55:02.708669

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "879e3970c027"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("max_number_of_players", sa.Integer(), nullable=True),
        sa.Column("number_of_turns", sa.Integer(), nullable=True),
        sa.Column("board_dimensions", sa.String(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_id"), "game", ["id"], unique=False)
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_player_id"), "player", ["id"], unique=False)
    op.create_index(op.f("ix_player_name"), "player", ["name"], unique=False)
    op.create_table(
        "participant",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("game_id", "player_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("participant")
    op.drop_index(op.f("ix_player_name"), table_name="player")
    op.drop_index(op.f("ix_player_id"), table_name="player")
    op.drop_table("player")
    op.drop_index(op.f("ix_game_id"), table_name="game")
    op.drop_table("game")
    # ### end Alembic commands ###
